runtime: python310  # 选择 Python 3.10 运行环境
entrypoint: gunicorn -b :$PORT group8project.wsgi  # 运行 Django
env_variables:
  DATABASE_NAME: "sql_training"
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "database_group8"
  DATABASE_HOST: "34.72.11.31"
  DATABASE_PORT: "5432"

handlers:
- url: /static
  static_dir: staticfiles/
- url: /.*
  script: auto

