# Generated by Django 4.2 on 2025-04-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorsRecord',
            fields=[
                ('error_id', models.AutoField(primary_key=True, serialize=False)),
                ('error_content', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'errors_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_timestamp', models.DateTimeField()),
                ('logout_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('login_status', models.BooleanField()),
            ],
            options={
                'db_table': 'login_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('llmadvice', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('latest_advice_from_llm', models.CharField(blank=True, max_length=255, null=True)),
                ('finished_country', models.CharField(blank=True, max_length=50, null=True)),
                ('finished_task', models.CharField(blank=True, max_length=255, null=True)),
                ('unfinish_task', models.CharField(blank=True, max_length=255, null=True)),
                ('unfinish_country', models.CharField(blank=True, max_length=50, null=True)),
                ('progress_percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'queries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_content', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'query_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('tname', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.DateField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(blank=True, max_length=10, null=True)),
                ('ispassed', models.BooleanField(blank=True, null=True)),
                ('issuedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.users')),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.users')),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'traveler',
                'managed': False,
            },
        ),
    ]
